USE [Delivery]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Despachos_Historial](
	[Número de pedido] [nvarchar](50) NULL,
	[Remito] [nvarchar](50) NULL,
	[T&T] [nvarchar](50) NULL,
	[Cuid] [nvarchar](50) NULL,
	[Fecha de Creacion del Pedido] [datetime] NULL,
	[Fecha ultimo estado de MEC] [datetime] NULL,
	[N° Cuenta] [nvarchar](50) NULL,
	[Factura de venta] [nvarchar](50) NULL,
	[Estado] [nvarchar](50) NULL,
	[Fulfillment Status] [nvarchar](50) NULL,
	[Tracking Status] [nvarchar](50) NULL,
	[Estado MEC] [nvarchar](50) NULL,
	[Descripción estado MEC] [nvarchar](50) NULL,
	[Tipo Gestión] [nvarchar](50) NULL,
	[Tipo Producto] [nvarchar](50) NULL,
	[Descripcion del Producto] [nvarchar](100) NULL,
	[NMU] [nvarchar](50) NULL,
	[IMEI-IMSI] [nvarchar](50) NULL,
	[Canal Venta] [nvarchar](50) NULL,
	[Equipo Creador] [nvarchar](50) NULL,
	[Usuario Creador] [nvarchar](50) NULL,
	[Bodega Delivery] [nvarchar](50) NULL,
	[Operador Logistico] [nvarchar](50) NULL,
	[Tipo de entrega] [nvarchar](50) NULL,
	[ID Contrato distribucion] [nvarchar](50) NULL,
	[CP] [nvarchar](50) NULL,
	[Sucursal de Distribución] [nvarchar](50) NULL,
	[Destinatario] [nvarchar](50) NULL,
	[Domicilio del Destinatario] [nvarchar](250) NULL,
	[Provincia] [nvarchar](50) NULL,
	[Localidad del Destinatario] [nvarchar](50) NULL,
	[Estado del Correo] [nvarchar](50) NULL,
	[Estado Detallado] [nvarchar](50) NULL,
	[Ultima Novedad] [nvarchar](100) NULL,
	[Fecha Ultima Novedad] [datetime] NULL,
	[Motivo Novedad Final] [nvarchar](250) NULL,
	[Fecha Alta] [datetime] NULL,
	[Hora Alta] [datetime] NULL,
	[Fecha Admisión] [datetime] NULL,
	[Hora Admisión] [datetime] NULL,
	[Fecha Inicio Distribución] [datetime] NULL,
	[Hora Inicio Distribución] [datetime] NULL,
	[Fecha Ingreso a Sucursal de Distribución] [datetime] NULL,
	[Hora Ingreso Sucursal de Distribución] [datetime] NULL,
	[Fecha 1er visita] [datetime] NULL,
	[Hora 1er visita] [datetime] NULL,
	[Motivo 1er visita] [nvarchar](250) NULL,
	[Fecha 2da visita] [datetime] NULL,
	[Hora 2da visita] [datetime] NULL,
	[Motivo 2da visita] [nvarchar](250) NULL,
	[Fecha 3er visita] [datetime] NULL,
	[Hora 3er visita] [datetime] NULL,
	[Motivo 3er visita] [nvarchar](250) NULL,
	[Fecha Ingreso a Custodia] [datetime] NULL,
	[Hora Ingreso a Custodia] [datetime] NULL,
	[Días Restantes de Custodia] [nvarchar](50) NULL,
	[Domicilio de la Sucursal] [nvarchar](150) NULL,
	[Datos del Receptor] [nvarchar](150) NULL,
	[Geolocalizacion] [nvarchar](250) NULL,
	[Constancia electrónica de entrega] [nvarchar](250) NULL,
	[Zona de Entrega] [nvarchar](50) NULL,
	[Efectividad de Entrega] [int] NULL,
	[LD FF] [int] NULL,
	[LD PROCES] [int] NULL,
	[LD ENTREGA] [int] NULL,
	[LD TOTAL] [int] NULL,
	[Promesa] [int] NULL,
	[GAP] [int] NULL,
	[Cumple Promesa] [nvarchar](2) NULL,
	[Avance de la Distribucion] [nvarchar](max) NULL,
	[Zona Correo] [nvarchar](50) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


