INSERT INTO dbo.Tabla_final (REMITO, FECHA, HORA, MOTIVO, NOMBRE, DIRECCION, EMAIL, PRODUCTO, PRECIO)
SELECT
    TU.REMITO,
    TU.FECHA,
    TU.HORA,
    TU.MOTIVO,
    COALESCE(T1.NOMBRE, T2.NOMBRE) AS NOMBRE,
    COALESCE(T1.DIRECCION, T2.DIRECCION) AS DIRECCION,
    COALESCE(T1.EMAIL, T2.EMAIL) AS EMAIL,
    COALESCE(T1.PRODUCTO, T2.PRODUCTO) AS PRODUCTO,
    COALESCE(T1.PRECIO, T2.PRECIO) AS PRECIO
FROM dbo.Table_Unica AS TU
LEFT JOIN dbo.Table_1 AS T1 ON TU.REMITO = T1.REMITO
LEFT JOIN dbo.Table_2 AS T2 ON TU.REMITO = T2.REMITO;